package com.myst.world.entities;

public enum EntityType {
    PLAYER,
    BULLET,
    ITEM_APPLE,
    ITEM_MED_KIT,
    ITEM_INVINCIBILITY_POTION,
    ITEM_INFINITE_BULLETS_POTION,
    ITEM_SPIKES_HIDDEN,
    ITEM_SPIKES_REVEALED,
    ITEM_BULLETS_SMALL,
    ITEM_BULLETS_BIG,
    ITEM_LIGHT_TRAP
}
